In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler

#### 1. Baca data

In [2]:
df = pd.read_excel('data/gaji.xlsx')
df

    NEGARA  USIA     GAJI BELI
0   France  44.0  58000.0   No
1    Spain  27.0  48000.0  Yes
2  Germany   NaN  64000.0   No
3    Spain  35.0  62000.0  Yes
4  Germany  40.0  54000.0  Yes
5   France  35.0      NaN  Yes
6    Spain  38.0  52000.0   No
7   France  48.0  79000.0  Yes
8  Germany  55.0  83000.0   No
9   France  32.0  68000.0  Yes

##### 2. Isi field kosong dengan rata-rata (fillna)

In [3]:
df["USIA"] = df["USIA"].fillna(df["USIA"].mean())
df["GAJI"] = df["GAJI"].fillna(df["GAJI"].mean())
df

    NEGARA       USIA          GAJI BELI
0   France  44.000000  58000.000000   No
1    Spain  27.000000  48000.000000  Yes
2  Germany  39.333333  64000.000000   No
3    Spain  35.000000  62000.000000  Yes
4  Germany  40.000000  54000.000000  Yes
5   France  35.000000  63111.111111  Yes
6    Spain  38.000000  52000.000000   No
7   France  48.000000  79000.000000  Yes
8  Germany  55.000000  83000.000000   No
9   France  32.000000  68000.000000  Yes

##### 3. Scaler Z-Score untuk USIA dan GAJI

In [4]:
scaler = StandardScaler()
df_zscore = scaler.fit_transform(df[["USIA", "GAJI"]])
df["Usia_ZScore"] = df_zscore[:, 0]
df["Gaji_ZScore"] = df_zscore[:, 1]
df[["USIA", "GAJI", "Usia_ZScore", "Gaji_ZScore"]]

        USIA          GAJI  Usia_ZScore  Gaji_ZScore
0  44.000000  58000.000000     0.608581    -0.479776
1  27.000000  48000.000000    -1.608392    -1.418469
2  39.333333  64000.000000     0.000000     0.083439
3  35.000000  62000.000000    -0.565111    -0.104299
4  40.000000  54000.000000     0.086940    -0.855253
5  35.000000  63111.111111    -0.565111     0.000000
6  38.000000  52000.000000    -0.173880    -1.042992
7  48.000000  79000.000000     1.130221     1.491478
8  55.000000  83000.000000     2.043092     1.866955
9  32.000000  68000.000000    -0.956341     0.458916

#### 4. Normalisasi MinMax 0-1 untuk USIA dan GAJI

In [5]:
minmax_01 = MinMaxScaler(feature_range=(0, 1))
df_minmax_01 = minmax_01.fit_transform(df[["USIA", "GAJI"]])
df["Usia_MinMax_01"] = df_minmax_01[:, 0]
df["Gaji_MinMax_01"] = df_minmax_01[:, 1]
df[["USIA", "GAJI", "Usia_MinMax_01", "Gaji_MinMax_01"]]

        USIA          GAJI  Usia_MinMax_01  Gaji_MinMax_01
0  44.000000  58000.000000        0.607143        0.285714
1  27.000000  48000.000000        0.000000        0.000000
2  39.333333  64000.000000        0.440476        0.457143
3  35.000000  62000.000000        0.285714        0.400000
4  40.000000  54000.000000        0.464286        0.171429
5  35.000000  63111.111111        0.285714        0.431746
6  38.000000  52000.000000        0.392857        0.114286
7  48.000000  79000.000000        0.750000        0.885714
8  55.000000  83000.000000        1.000000        1.000000
9  32.000000  68000.000000        0.178571        0.571429

#### 5. Normalisasi MinMax 1-10 untuk USIA dan GAJI

In [6]:
minmax_110 = MinMaxScaler(feature_range=(1, 10))
df_minmax_110 = minmax_110.fit_transform(df[["USIA", "GAJI"]])
df["Usia_MinMax_110"] = df_minmax_110[:, 0]
df["Gaji_MinMax_110"] = df_minmax_110[:, 1]
df[["USIA", "GAJI", "Usia_MinMax_110", "Gaji_MinMax_110"]]

        USIA          GAJI  Usia_MinMax_110  Gaji_MinMax_110
0  44.000000  58000.000000         6.464286         3.571429
1  27.000000  48000.000000         1.000000         1.000000
2  39.333333  64000.000000         4.964286         5.114286
3  35.000000  62000.000000         3.571429         4.600000
4  40.000000  54000.000000         5.178571         2.542857
5  35.000000  63111.111111         3.571429         4.885714
6  38.000000  52000.000000         4.535714         2.028571
7  48.000000  79000.000000         7.750000         8.971429
8  55.000000  83000.000000        10.000000        10.000000
9  32.000000  68000.000000         2.607143         6.142857

#### 6. Gabungan dataframe asli + hasil proses

In [7]:
df

,NEGARA,USIA,GAJI,BELI,Usia_ZScore,Gaji_ZScore,Usia_MinMax_01,Gaji_MinMax_01,Usia_MinMax_110,Gaji_MinMax_110
0,France,44.000000,58000.000000,No,0.608581,-0.479776,0.607143,0.285714,6.464286,3.571429
1,Spain,27.000000,48000.000000,Yes,-1.608392,-1.418469,0.000000,0.000000,1.000000,1.000000
2,Germany,39.333333,64000.000000,No,0.000000,0.083439,0.440476,0.457143,4.964286,5.114286
3,Spain,35.000000,62000.000000,Yes,-0.565111,-0.104299,0.285714,0.400000,3.571429,4.600000
4,Germany,40.000000,54000.000000,Yes,0.086940,-0.855253,0.464286,0.171429,5.178571,2.542857
5,France,35.000000,63111.111111,Yes,-0.565111,0.000000,0.285714,0.431746,3.571429,4.885714
6,Spain,38.000000,52000.000000,No,-0.173880,-1.042992,0.392857,0.114286,4.535714,2.028571
7,France,48.000000,79000.000000,Yes,1.130221,1.491478,0.750000,0.885714,7.750000,8.971429
8,Germany,55.000000,83000.000000,No,2.043092,1.866955,1.000000,1.000000,10.000000,10.000000
9,France,32.000000,68000.000000,Yes,-0.956341,0.458916,0.178571,0.571429,2.607143,6.142857

#### 7. Export hasil.xlsx

In [9]:
df.to_excel("Hasil.xlsx", index=False)
print("Berhasil")

Berhasil